// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'CommonFooter': typeof import('../components/common/Footer.vue')['default'],
    'CommonGoodCard': typeof import('../components/common/GoodCard.vue')['default'],
    'CommonMap': typeof import('../components/common/Map.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
