// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'CommonBanner': typeof import('../components/common/banner.vue')['default'],
    'CommonFooter': typeof import('../components/common/Footer.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
